### ISSUE TITLE
2.0.0 doesnt seem to work

### ISSUE THREAD

**Issue by ghost** [DaPigGuy/PiggyAuth#1]
Added this onto my server and it doesnt work. When i got to /plugins it shows red :p piggy fix it or else no mud 😊 love youuu no homo.

**Comment by DaPigGuy** [comment]
Works for me. Im using the latest version here.

**Comment by DaPigGuy** [comment]
Fixed this issue.

**Comment by vcraftPE** [comment]
dude anyway to transform server auth data to this auth i have over 1700 user registered

**Comment by DaPigGuy** [comment]
Maybe. Ill work on a way. Are you using yml, sql3, or mysql on ServerAuth

**Comment by VCraftMCPE** [comment]
yml

**Comment by Aericio** [comment]
hestillwillnotdoit.yml
