### ISSUE TITLE
Please add Turkish language

### ISSUE THREAD

**Issue by SuperAdam47** [DaPigGuy/PiggyAuth#100]
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [x] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuth
- * [ ] Have a detailed title like "Players are being kicked randomly"
- * [ ] Provide any crash dumps or errors

#### **Data Provider:**

- [ ] MySQL
- [ ] SQLite
- [ ] YAML
- [ ] JSON

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**
YOUR AUTH PLUGIN AWESOME!

**Comment by SalmonDE** [comment]
If you wish to have turkish as language feel free to add it to PiggyAuth via a pr.
I'm not aware of any direct contributor of PiggyAuth who decently speaks turkish, so this has to be done by an external person.

I'll close this, but I'd be very happy if you would decide to translate PiggyAuth to turkish.

**Comment by SuperAdam47** [comment]
Okay, then I'm starting to work.
