### ISSUE TITLE
UUID Login

### ISSUE THREAD

**Issue by Aericio** [DaPigGuy/PiggyAuth#11]
When you use UUID login, it sends you the message to type pass to login (you don't need to though)
![image](https://cloud.githubusercontent.com/assets/16523741/20127450/39e6f6ae-a5e3-11e6-85e3-1664340254f0.png)
You should make it so it doesn't show that if you use UUID login so people don't accidentally type their passwords in chat and "Oops! Everyone hack me!"

**Comment by DaPigGuy** [comment]
Passwords are already blocked. 😜

**Comment by Aericio** [comment]
I just remembered, but can you still remove that part and make the "You have been authenticated" to "You have been authenticated by UUID" or something?

**Comment by DaPigGuy** [comment]
Ok.
