### ISSUE TITLE
Remove effects AFTER typing in the email or "none"

### ISSUE THREAD

**Issue by inxomnyaa** [DaPigGuy/PiggyAuth#13]
Its annoying. you register, type in PW, PW and have no more effects. you can move etc. then you want to chat and tada: "Invalid email"

**Comment by Aericio** [comment]
It does say that. In the config at least.

**Comment by inxomnyaa** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/20208269/44f6c2e8-a7ed-11e6-98c2-a89debd71d7c.png)

**Comment by DaPigGuy** [comment]
Alright.

**Comment by DaPigGuy** [comment]
Use the Update 2.0.1 issue though.
