### ISSUE TITLE
Boss Bar

### ISSUE THREAD

**Issue by ghost** [DaPigGuy/PiggyAuth#14]
Boss bar not work.

Enter with 0.16.1 ,windows 10.

**Comment by DaPigGuy** [comment]
Works with 0.16.1 iOS, latest version.

**Comment by DaPigGuy** [comment]
Are you using latest version?

**Comment by DaPigGuy** [comment]
PS: Please use the Update 2.0.1 issue.

**Comment by ghost** [comment]
I'm using genisys and not work.

**Comment by ghost** [comment]
On windows 10 @MCPEPIG

**Comment by DaPigGuy** [comment]
Oh, it's fixed now. Sorry, there were incompatibility issues with genisys and piggyauth.
