### ISSUE TITLE
When you set Adventure mode to true, then a player tries to join a Whitelisted server

### ISSUE THREAD

**Issue by starterdragon** [DaPigGuy/PiggyAuth#17]
"Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'PiggyAuth v2.0.1': Argument 1 passed to pocketmine\Player::setGamemode() must be of the type integer, null given, called in phar://C:/Users/Administrator/Desktop/RP/plugins/PiggyAuth (2).phar/src/PiggyAuth/Main.php on line 415 on PiggyAuth\EventListener

 TypeError: "Argument 1 passed to pocketmine\Player::setGamemode() must be of the type integer, null given, called in phar://C:/Users/Administrator/Desktop/RP/plugins/PiggyAuth (2).phar/src/PiggyAuth/Main.php on line 415" (EXCEPTION) in "/src/pocketmine/Player" at line 1369

**Comment by DaPigGuy** [comment]
Fixed.
