### ISSUE TITLE
Slapper issue?? again??

### ISSUE THREAD

**Issue by starterdragon** [DaPigGuy/PiggyAuth#18]
TypeError: "Argument 1 passed to PiggyAuth\Main::isAuthenticated() must be an instance of pocketmine\Player, instance of slapper\entities\SlapperHuman given, called in phar://C:/Users/Administrator/Desktop/RP/plugins/PiggyAuth (2).phar/src/PiggyAuth/EventListener.php on line 186" (EXCEPTION) in "/PiggyAuth (2).phar/src/PiggyAuth/Main" at line 148

This happens with my other issue (Joining a whitelisted server)... idk they might have connection

**Comment by DaPigGuy** [comment]
Are you sure you're using the latest version?
