### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by ghost** [DaPigGuy/PiggyAuth#25]
How to disable database :/? I am not using it but if I try to load plugin without database it shows this error:

[Server thread/CRITICAL]: Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "/PiggyAuth-master/src/PiggyAuth/Databases/SQLite3" at line 15

Please, I want to use this auth. It looks really great!

**Comment by Thunder33345** [comment]
but it needs a database to store player data?

**Comment by ghost** [comment]
Cannot be it stored in config?

**Comment by ghost** [comment]
So, how can I setup SQLite3 database?

**Comment by Thunder33345** [comment]
not a maintainer, but nope not for this plugin, i think it just creates it itself
maybe the plugin dont have permission to create the players.sql
not very sure tho

**Comment by DaPigGuy** [comment]
Do you have sqlite3 files in your bin folder?

**Comment by Aericio** [comment]
if you are in windows, download [this](https://www.opendll.com/index.php?file-download=php_sqlite3.dll&arch=32bit&version=5.4.3.0&dsc=SQLite3) and drop it in `bin/php`

**Comment by ghost** [comment]
Okay, I will test. Thank you!

**Comment by DaPigGuy** [comment]
Is it working?

**Comment by ghost** [comment]
No :/. I will create MySQL database and host it on. I will never more change Auth plugin. I think this is perfect.

**Comment by DaPigGuy** [comment]
You getting any new errors with SQLite3?

**Comment by ghost** [comment]
Yes. this. [Server thread/CRITICAL]: Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "/PiggyAuth-master/src/PiggyAuth/Databases/SQLite3" at line 15

**Comment by DaPigGuy** [comment]
Can you show me your php.ini file & php_sqlite3.dll in your bin folder?

**Comment by ghost** [comment]
Yes. php_sqlite3.dll - https://www.opendll.com/index.php?file-download=php_sqlite3.dll&arch=32bit&version=5.4.3.0&dsc=SQLite3
php.ini - wait, I must upload it on cloud.

**Comment by ghost** [comment]
; Compiled by SalmonDE
zend.enable_gc = On
max_execution_time = 0
memory_limit = 256M
error_reporting = -1
display_errors = stderr
display_startup_errors = On
register_argc_argv = On
default_charset = "UTF-8"
include_path = ".;.\ext"
extension_dir = "./"
enable_dl = On
allow_url_fopen = On
extension=php_weakref.dll
extension=php_curl.dll
extension=php_mysqli.dll
extension=php_sqlite3.dll
extension=php_sockets.dll
extension=php_mbstring.dll
extension=php_yaml.dll
extension=php_pthreads.dll
extension=php_openssl.dll
extension=php_com_dotnet.dll
extension=php_gd2.dll
zend_extension=php_opcache.dll
cli_server.color = On
phar.readonly = Off
phar.require_hash = On
zend.assertions=-1
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.save_comments=1
opcache.load_comments=1
opcache.fast_shutdown=0
opcache.optimization_level=0xffffffff
date.timezone=UTC

**Comment by DaPigGuy** [comment]
It should work fine. Does your server have permission to edit files?

**Comment by ghost** [comment]
I think yes. If I execute any command and it edits config (for example)?

**Comment by ghost** [comment]
I download latest update and try it.

**Comment by ghost** [comment]
I have this error with latest update. [17:20:34] [Server thread/INFO]: Enabling PiggyAuth v2.0.1
[17:20:34] [Server thread/CRITICAL]: ClassNotFoundException: "Class SQLite3 not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by DaPigGuy** [comment]
... What did you do?

**Comment by ghost** [comment]
Nothing. I only deleted old version. downloaded version from GitHub (the newest) and pasted.

**Comment by DaPigGuy** [comment]
I think you did something wrong. Try again, I'm on the latest version and no problems.

**Comment by ghost** [comment]
I have SQLite3 class in src/PiggyAuth/Databases.

**Comment by DaPigGuy** [comment]
Try again...

**Comment by ghost** [comment]
I think the plugin did not create SQLite3 file with players data.

**Comment by DaPigGuy** [comment]
It should, check PiggyAuth folder for players.db

**Comment by ghost** [comment]
Okay.

**Comment by ghost** [comment]
I have in PiggyAuth folder only config.yml.

**Comment by ghost** [comment]
I try it again.

**Comment by MCPEPIG** [comment]
I think the server can't edit files.

**Comment by ghost** [comment]
[Server thread/CRITICAL]: Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "/PiggyAuth-master/src/PiggyAuth/Databases/SQLite3" at line 15

What can I do with it? I am running my test server on Windows 32-bit. I have the latest version of binaries and Genisys server sofware.

**Comment by DaPigGuy** [comment]
Try out FactionsPro & see if it creates the database. It uses SQLite3 too. https://github.com/Awzaw/FactionsPro/blob/master/src/FactionsPro/FactionMain.php

**Comment by ghost** [comment]
Yes.

**Comment by DaPigGuy** [comment]
It creates a database?

**Comment by ghost** [comment]
No. I have the same error.

**Comment by DaPigGuy** [comment]
It's your problem not the plugins.

**Comment by ghost** [comment]
I will test it on hosting. Wait please.

**Comment by ghost** [comment]
It is working on hosting server.

**Comment by DaPigGuy** [comment]
It is your problem them.

**Comment by ghost** [comment]
Yes. Thank you for everything!
