### ISSUE TITLE
Non-logged in/non-registered Players

### ISSUE THREAD

**Issue by ghost** [DaPigGuy/PiggyAuth#28]
Could you add something like if player is not registered or logged in, it gets random username, for example Player1, Player2, etc. and it can do everything like normal player but it will not can execute commands? I hope I was clear enough.

**Comment by DaPigGuy** [comment]
Like lbsg?

**Comment by DaPigGuy** [comment]
PS please request in #10

**Comment by ghost** [comment]
Yes, something like this (LBSG).

**Comment by DaPigGuy** [comment]
Ok, I might add it in next update.

**Comment by ghost** [comment]
It would be really awesome! Thank you very much.

**Comment by DaPigGuy** [comment]
#39
