### ISSUE TITLE
More Languages

### ISSUE THREAD

**Issue by ghost** [DaPigGuy/PiggyAuth#29]
Will you add more languages? I could help you with translation.

**Comment by DaPigGuy** [comment]
Yeah.

**Comment by ghost** [comment]
So, can I translate plugin messages in config.yml to Czech language and post them here?

**Comment by DaPigGuy** [comment]
Just do the messages & make a lang_cze.yml. I'll add multi language support later.

**Comment by ghost** [comment]
Okay. I will let you know when I finish.

**Comment by ghost** [comment]
Can I ask you? I think this join-message: "&6This server requires an account." would be better with "&6This server requires a registration.", do not you think?

**Comment by ghost** [comment]
Can I make better english translation too please? You can check it then, ok?

**Comment by DaPigGuy** [comment]
Ok, I'm testing out lang support.

**Comment by ghost** [comment]
Well.

**Comment by Aericio** [comment]
I think making the messages similar to SimpleAuth would be better.

**Comment by ghost** [comment]
Wait please :-), I have not finished.

**Comment by DaPigGuy** [comment]
I've finished

**Comment by ghost** [comment]
I am finishing. I am improving colors too.

**Comment by DaPigGuy** [comment]
... Colors should be orange, green, or red. Orange: Default Green: Success Red: Error

**Comment by ghost** [comment]
Yes, I know. I thought yellow is better.

**Comment by DaPigGuy** [comment]
Ok.

**Comment by ghost** [comment]
I did nothing with red and green.

**Comment by DaPigGuy** [comment]
Make a pull request when you're done.

**Comment by DaPigGuy** [comment]
And check out how I did lang_eng

**Comment by ghost** [comment]
Yes. I copied lang_eng and then I translated it.

**Comment by DaPigGuy** [comment]
Ok.

**Comment by ghost** [comment]
Are you here?

**Comment by DaPigGuy** [comment]
Yeah.

**Comment by DaPigGuy** [comment]
Just testing out PMMP resource pack support.

**Comment by ghost** [comment]
Yes. I have finished in a few seconds.

**Comment by DaPigGuy** [comment]
Done?

**Comment by ghost** [comment]
Yes. Czech and English language too. What now?

**Comment by ghost** [comment]
Can I post it there as text (.txt) and you check it and change it on yaml (.yml)?

**Comment by DaPigGuy** [comment]
Sure.

**Comment by ghost** [comment]
Well. Here is it.

**Comment by ghost** [comment]
[lang_eng.txt](https://github.com/MCPEPIG/PiggyAuth/files/836965/lang_eng.txt)

**Comment by ghost** [comment]
[lang_cze.txt](https://github.com/MCPEPIG/PiggyAuth/files/836966/lang_cze.txt)

**Comment by ghost** [comment]
I hope it is good. You can check yourself.

**Comment by ghost** [comment]
What do you think?

**Comment by DaPigGuy** [comment]
Don't like english one much.

**Comment by ghost** [comment]
Yes.

**Comment by ghost** [comment]
What do you mean?

**Comment by ghost** [comment]
English does not work well?

**Comment by DaPigGuy** [comment]
I've changed colors back & changed one thing for czech.

**Comment by DaPigGuy** [comment]
I like mines better. 😛

**Comment by ghost** [comment]
EDIT: I tested the latest commit when it returns false and it works good but it gets lagged for a few seconds after email registration.

**Comment by ghost** [comment]
Yes.

**Comment by ghost** [comment]
I am happy that I could help :).

**Comment by DaPigGuy** [comment]
No, that's normal. It has to wait for the task to complete.

**Comment by ghost** [comment]
Well.

**Comment by DaPigGuy** [comment]
Pushed commit. PiggyAuth now has czech. I'm going to create a new issue for this.

**Comment by DaPigGuy** [comment]
Thanks!

**Comment by ghost** [comment]
Yeah.

**Comment by DaPigGuy** [comment]
#31
