### ISSUE TITLE
Ask for auth for non-xbox users

### ISSUE THREAD

**Issue by dries-c** [DaPigGuy/PiggyAuth#3]
ask for auth if a player is not logged in with xbox account

register: auth
login1xwithxbox: auth
login2x: xbox login
login3xwithoutxbox: auth

**Comment by DaPigGuy** [comment]
I will add this when Genisys finishes their xbox-auth.

**Comment by dries-c** [comment]
it will be done in 2 days i think

**Comment by DaPigGuy** [comment]
Doing this now!

**Comment by DaPigGuy** [comment]
Been delayed due to problems.

**Comment by DaPigGuy** [comment]
The feature no longer works for ClearSky and there's no api for genisys. Closing. Once clearsky fixes it, this should work without any updates.

**Comment by DaPigGuy** [comment]
Also will add support for genisys if they add an api
