### ISSUE TITLE
Email + BossBar Bug

### ISSUE THREAD

**Issue by ghost** [DaPigGuy/PiggyAuth#30]
If I write my password in the chat, then again password and then email it shows "Invalid email.". My email is wotblitzcz@email.cz. And I see boss (wither) in front of me if I have enabled boss bar.
![img_0629](https://cloud.githubusercontent.com/assets/25885263/23834534/38c6b2ce-0758-11e7-9c83-a77a284133d5.PNG)

**Comment by Aericio** [comment]
Report bugs at #10

**Comment by ghost** [comment]
Okay, sorry. Thanks for info!

**Comment by DaPigGuy** [comment]
The wither is needed for boss bar.

**Comment by DaPigGuy** [comment]
If your email doesn't work, just use none

**Comment by ghost** [comment]
But I do not know why it does not work. And if I write none it shows the same - "Invalid email."

**Comment by ghost** [comment]
And can you spawn this wither on a different place? I think e. g. under 0 (y = 0).

**Comment by Thunder33345** [comment]
i think we should just have a config for using an old school email regex

**Comment by ghost** [comment]
So, how to make it working?

**Comment by Aericio** [comment]
MySQL or SQLite3? Any errors in console?

**Comment by ghost** [comment]
SQLite3, no errors.

**Comment by Aericio** [comment]
What server core are you using? PMMP?

**Comment by ghost** [comment]
No, Genisys.

**Comment by Aericio** [comment]
Will test.

**Comment by ghost** [comment]
Yes.

**Comment by Aericio** [comment]
![image](https://cloud.githubusercontent.com/assets/16523741/23836353/dc111f84-071a-11e7-91c3-15a9294b5c05.png)
lmao glitchy as hell.

**Comment by ghost** [comment]
XD Will it be fixed?

**Comment by Aericio** [comment]
Before I can confirm password, it sends me the "Now type in your email" message. I get errors though:
![image](https://cloud.githubusercontent.com/assets/16523741/23836416/d59b182a-071b-11e7-8db8-2334e19e8891.png)

**Comment by DaPigGuy** [comment]
@lolmanz0  Aericio That means something went wrong when it was validating. Are you sure you have the correct domain & api keys?

**Comment by DaPigGuy** [comment]
@lolmanz0  You also need these 2 files in your bin folder:  https://github.com/MCPEPIG/PiggyAuth-MailGunFiles

**Comment by Aericio** [comment]
I haven't set it... can you add a switch to it :3

**Comment by DaPigGuy** [comment]
@Thunder33345 It now checks with filter_var() if first result returns null.

**Comment by DaPigGuy** [comment]
New commit makes it use a 2nd method if first one fails.

**Comment by Aericio** [comment]
I added my MailGun credentials, still gives me the "Trying to get property of blah"

**Comment by DaPigGuy** [comment]
You have certificate in the bin folder?

**Comment by Aericio** [comment]
![image](https://cloud.githubusercontent.com/assets/16523741/23836480/16b0ad2e-071d-11e7-8966-0b2728037062.png)

**Comment by DaPigGuy** [comment]
What about php.ini? Did you use one provided by me?

**Comment by Aericio** [comment]
Yes.

**Comment by DaPigGuy** [comment]
Double check your credentials. I don't have any issues.

**Comment by Aericio** [comment]
Send me your bins on telegram :D

**Comment by Thunder33345** [comment]
@MCPEPIG i dont trust if filter_var will do the trick
especially for weird short/very long domain name
something like search for @ and . should do
UNLESS are using email activation pin
what about people using same email? or using + to remove the one email policy?
