### ISSUE TITLE
Entity - Wither

### ISSUE THREAD

**Issue by ghost** [DaPigGuy/PiggyAuth#32]
Could you teleport* the entity (wither) at 0/0/0 (X/Y/Z)? I think it would be better.

**Comment by ghost** [comment]
*spawn at 0/0/0

**Comment by ghost** [comment]
Something like https://github.com/thebigsmileXD/BossBarAPI.

**Comment by DaPigGuy** [comment]
Done. It is now 25 blocks under the player.

**Comment by ghost** [comment]
Nice.

**Comment by Aericio** [comment]
Feature requests and bugs in #10 please :3
