### ISSUE TITLE
One More Message

### ISSUE THREAD

**Issue by ghost** [DaPigGuy/PiggyAuth#33]
I think you could add one more message on join (it could be optional too). Something like - "Welcome on {server}!". {server} = $this->getServer()->getName().

**Comment by ghost** [comment]
"&6ento server vyžaduje přihlášení." - There is missing T. Add it please :-). - "&6Tento server vyžaduje přihlášení."

**Comment by DaPigGuy** [comment]
Can't you do that manually? Like set one of the message to Message1\nWelcome to PigLand.

**Comment by DaPigGuy** [comment]
\n creates a new line.

**Comment by DaPigGuy** [comment]
And also, fixed.

**Comment by ghost** [comment]
Yeah. I forgot on \n.

**Comment by ghost** [comment]
Okay, I think that is all for now. #PiggyPOWER
