### ISSUE TITLE
Error when starting the Server!

### ISSUE THREAD

**Issue by PluginBOXone** [DaPigGuy/PiggyAuth#47]
[Tesseract] [09:43:35] ERROR> [PiggyAuth] Invalid API key.
[Tesseract] [09:43:35] ERROR> [PiggyAuth] Invalid public API key.

OS: Debian 8
Mcpe: 1.0.6
Version: Tesseract

**Comment by Thunder33345** [comment]
that's why i propose to have fallbacks like falling back onto using local regex verify emails and local mail()
which require a rewrite of the mailing part to make it flexible

**Comment by miguel456** [comment]
You need a valid MailGun API key (Not sure if that's the case). As per your other issue, there's nothing I can do. Srry!

**Comment by DaPigGuy** [comment]
@Thunder33345 It already exists. 
                if ($this->result == null) {
                    $this->result = filter_var(unserialize($this->email), FILTER_VALIDATE_EMAIL);
                }

**Comment by DaPigGuy** [comment]
You are missing MailGun API keys.

**Comment by Thunder33345** [comment]
but a more flexiable fallback? like allowing plugin to register other mail sender?
