### ISSUE TITLE
EventListener Error!

### ISSUE THREAD

**Issue by PluginBOXone** [DaPigGuy/PiggyAuth#48]
Notice: Undefined property: pocketmine\network\protocol\ContainerSetSlotPacket::$selectSlot in phar:///---------/plugins/PiggyAuth.phar/src/PiggyAuth/EventListener.php on line 352

OS: Debian 8
Version: Tesseract
V. 1.0.6

**Comment by DaPigGuy** [comment]
This plugin is only tested for PMMP.

**Comment by DaPigGuy** [comment]
Fixed.

**Comment by PluginBOXone** [comment]
Ok thx!
