### ISSUE TITLE
Add notice for supported server software

### ISSUE THREAD

**Issue by miguel456** [DaPigGuy/PiggyAuth#52]
I've been noticing people complaining about this plugin crashing and/or having other issues on other server software. This plugin was written for PMMP, not for other server software. Why not add a list of tested/supported server software (Besides PMMP) in clear view at the readme file or in a CONTRIBUTING.md?

**Comment by DaPigGuy** [comment]
Ok, will do later.

**Comment by DaPigGuy** [comment]
Done.
