### ISSUE TITLE
PlayerQuitEvent Error

### ISSUE THREAD

**Issue by PluginBOXone** [DaPigGuy/PiggyAuth#55]
Sorry I removed everything but i think you know me xD

When a player is joining (Console Output)

[Tesseract] [21:11:13] CRITICAL> "Das Event 'pocketmine\event\player\PlayerQuitEvent' konnte nicht an 'PiggyAuth v3.0.0.08' weitergegeben werden: Call to a member function isAuthenticated() on null in PiggyAuth\EventListener"
[Tesseract] [21:11:13] CRITICAL> Error: "Call to a member function isAuthenticated() on null" (EXCEPTION) in "/plugins/PiggyAuth-master/src/PiggyAuth/Main" at line 713

**Comment by PluginBOXone** [comment]
And I am using your newest version!

**Comment by DaPigGuy** [comment]
...

**Comment by MCPEPIG** [comment]
Are players being kicked before fully joining?

**Comment by DaPigGuy** [comment]
I'm not having any issues you are having...

**Comment by MCPEPIG** [comment]
Try with SQLite3

**Comment by PluginBOXone** [comment]
Maybe it is the EventListener or look into the Main.php at Line 713

**Comment by DaPigGuy** [comment]
It's fine...

**Comment by MCPEPIG** [comment]
Is your server whitelisted?...

**Comment by MCPEPIG** [comment]
Or full?

**Comment by DaPigGuy** [comment]
This happens if server is whitelisted or full as the session isn't created.

**Comment by PluginBOXone** [comment]
Oh Okay... my server is whitelisted!

**Comment by DaPigGuy** [comment]
Thanks for reporting all these bugs. Just fixed this.

**Comment by PluginBOXone** [comment]
I know it isn't an Error but can you please help me? I turned on (in my start.sh file) DO LOOP = YES
And started the server... I changed it to DO LOOP = NO and restarted the Server but the server is running and doesn't turns off! How can i deactivate DO LOOP? Please help me

**Comment by DaPigGuy** [comment]
What???

**Comment by PluginBOXone** [comment]
Forget it

**Comment by Thunder33345** [comment]
for future references 
pid=$(lsof -i:$PORT -t);kill -TERM $pid || kill -KILL $pid

**Comment by PluginBOXone** [comment]
Were do I have to put this code in?

**Comment by lolmanz0** [comment]
Kid... #PluginBOXone

**Comment by ghost** [comment]
There is not a server forum...
