### ISSUE TITLE
Should we add a banning system to PiggyAuth?

### ISSUE THREAD

**Issue by DaPigGuy** [DaPigGuy/PiggyAuth#57]
Should we add a banning system into PiggyAuth? 

For yes, 👍 
For no, 👎

**Comment by ghost** [comment]
Yas!

**Comment by MCPEPIG** [comment]
Then why did you dislike?...

**Comment by ghost** [comment]
Can you make a plugin where you can warren players then a ban if they get enough points

**Comment by NFGamerMC** [comment]
Also, I didn't dislike. Reaload

**Comment by Thunder33345** [comment]
i think it should be separated

**Comment by Aericio** [comment]
This should be a separate plugin.

**Comment by PluginBOXone** [comment]
Yes!

**Comment by miguel456** [comment]
Yussssss
That would be awesome
The plugin could have extension modules (such as the banning system) that could be just dropped in the plugins folder and enabled/disabled separately by the main plugin

**Comment by DaPigGuy** [comment]
It has been decided that we will add a banning system, but as @miguel456 suggested, we will do modules.

**Comment by Thunder33345** [comment]
at least it isnt bind to the main plugin, i think the main is currently too bulky i would appreciate a flexibility rewrite

**Comment by DaPigGuy** [comment]
This will come in the next update.
