### ISSUE TITLE
Email Support

### ISSUE THREAD

**Issue by VCraftMCPE** [DaPigGuy/PiggyAuth#6]
1- email support 
2- forget password send pin to email
3-chat register/login
and im using piggy auth because data bases

**Comment by DaPigGuy** [comment]
1 & 2 are planned, 3 is already added. Check your config.yml

**Comment by DaPigGuy** [comment]
Done, just waiting on the email server to be fixed by @xBeastMode

**Comment by DaPigGuy** [comment]
Fully finished.
