### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by ghost** [DaPigGuy/PiggyAuth#60]
Hello,
This is a feature request. Can you make it for unlogged in members they get a guest1038 tag. I can advertise that they must register to get there name shown? They can walk around the lobby without registration but they will have something like guest2828. Possibly edit in the config?

**Comment by Thunder33345** [comment]
if you want to fully change their username, you may have to retransfer them to the current server and change the username on the gamestart packet

**Comment by ghost** [comment]
I don't want to fully I just want them to have a random nickname until they login

**Comment by DaPigGuy** [comment]
That's already in the todo but fully change their username. If it's just a display name, they can do something on the account and it will be saved with the account name.
