### ISSUE TITLE
Auth is broken disables all commmands and clears invents...

### ISSUE THREAD

**Issue by PixelOG** [DaPigGuy/PiggyAuth#62]
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuth
- * [ ] Have a detailed title like "Players are being kicked randomly"
- * [ ] Provide any crash dumps or errors

#### **General**
[Tesseract] [02:58:13] CRITICAL> Error: "Cannot use object of type stdClass as array" (EXCEPTION) in "/PiggyAuth-master/src/PiggyAuth/Commands/RegisterCommand" at line 83
[Tesseract] [02:58:13] INFO> An unknown error occurred while attempting to perform this command
[Tesseract] [02:58:13] CRITICAL> Unhandled exception executing command 'reload' in reload: Cannot use object of type stdClass as array
[Tesseract] [02:58:13] CRITICAL> Error: "Cannot use object of type stdClass as array" (EXCEPTION) in "/PiggyAuth-master/src/PiggyAuth/Commands/RegisterCommand" at line 83

#### **Server Software:**
tesseract rotten apple

#### **Version of PiggyAuth:**
latest

#### **Data Provider:**

yaml
#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
Fixed error. PiggyAuth sends a blank inventory to players and blocks commands until they authenticate and therefore isn't a bug.

**Comment by Aericio** [comment]
problem i had, that's the error i sent you.

**Comment by Aericio** [comment]
+1
