### ISSUE TITLE
Boss bar doesn't show up

### ISSUE THREAD

**Issue by DaPigGuy** [DaPigGuy/PiggyAuth#66]
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuth
- * [ ] Have a detailed title like "Players are being kicked randomly"
- * [ ] Provide any crash dumps or errors

#### **General**

Boss bar doesn't show up
#### **Server Software:**

PMMP 
#### **Version of PiggyAuth:**

3.0.0.20
#### **Data Provider:**

- [x] MySQL
- [ ] SQLite
- [ ] YAML
- [ ] JSON

#### **Steps to Reproduce the Issue**

1.Get on or logout.

**Comment by AnUnknownPerson** [comment]
Are you using a superbar plugin or HUD plugin With it?

**Comment by DaPigGuy** [comment]
Nope.
