### ISSUE TITLE
Mailgun problem.

### ISSUE THREAD

**Issue by jerryzooyoyo** [DaPigGuy/PiggyAuth#72]
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [x] Be using PMMP
- * [x] Make sure the issue hasn't already been reported
- * [x] Make sure you are on the latest version of PMMP & PiggyAuth
- * [x] Have a detailed title like "Players are being kicked randomly"
- * [x] Provide any crash dumps or errors

#### **General**

In the Mailgun dashboard, I can see the api key, but where is the public api key ?
#### **Server Software:**

PMMP
#### **Version of PiggyAuth:**

3.0.0.20
#### **Data Provider:**

- [ ] MySQL
- [ ] SQLite
- [ ] YAML
- [x] JSON

#### **Steps to Reproduce the Issue**

1.Login Mailgun.
2.Go to dashboard.
3.Check the domain Information.

#### **Extra Information**

![domain](https://cloud.githubusercontent.com/assets/16357120/26038991/15fe6f4a-3947-11e7-9266-71faed28b37f.jpg)

**Comment by DaPigGuy** [comment]
Get it [here.](https://app.mailgun.com/app/dashboard)

**Comment by jerryzooyoyo** [comment]
@MCPEPIG Well...Could you show me with image ?
I've looked at the dashboard site...

**Comment by Aericio** [comment]
On the dashboard site, there will be a box on the right that says "API Keys"
