### ISSUE TITLE
 cannot register

### ISSUE THREAD

**Issue by ondraczsk** [DaPigGuy/PiggyAuth#73]
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuth
- * [ ] Have a detailed title like "Players are being kicked randomly"
- * [ ] Provide any crash dumps or errors

#### **General**

if i write email to chat when registrating, it write: CRITICAL> "Could not pass event 'pocketmine\event\player\PlayerChatEvent' to 'PiggyAuth v3.0.0.20': Cannot call constructor on PiggyAuth\EventListener
CRITICAL> Error: "Cannot call constructor" (EXCEPTION) in "/plugins/PiggyAuth_v3.0.0.19.phar/src/PiggyAuth/Tasks/ValidateEmailTask" at line 32

#### **Server Software:**

Tesseract linux
#### **Data Provider:**

- [ ] MySQL
- [ ] SQLite
- [ ] YAML
- [yes] JSON

**Comment by Aericio** [comment]
PiggyAuth doesn't support Tesseract.
