### ISSUE TITLE
email not working

### ISSUE THREAD

**Issue by XDqrkneZ** [DaPigGuy/PiggyAuth#77]
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuth
- * [ ] Have a detailed title like "Players are being kicked randomly"
- * [ ] Provide any crash dumps or errors

#### **Server Software:**

Tesseract
#### **Version of PiggyAuth:**

PiggyAuth version 3.0.0.19
#### **Data Provider:**

- [ ] MySQL I believe
- [ ] SQLite
- [ ] YAML
- [ ] JSON

#### **Steps to Reproduce the Issue**

1. I typed my email but nothing happened so I typed 'none' and it worked
2. the part where it asked for my email -> Now type in your email. Type 'none' to skip.

**Comment by DaPigGuy** [comment]
Latest version is 3.0.0.20...

**Comment by DaPigGuy** [comment]
but we no longer support Tesseract as of 3.0.0.20

**Comment by Aericio** [comment]
Try this on pmmp.
