### ISSUE TITLE
Login/Register have a bit delay

### ISSUE THREAD

**Issue by xinghao2003** [DaPigGuy/PiggyAuth#79]
- Be using PMMP
- Have a detailed title like "Players are being kicked randomly"

#### **General**
When player login or register after key in all details and enter it will delay

#### **Server Software:**
PMMP 3.0.0-ALPHA5

#### **Version of PiggyAuth:**
 3.0.0.20

#### **Data Provider:**
- JSON

#### **Steps to Reproduce the Issue**
1.Get in to server
2.Login / Register

**Comment by DaPigGuy** [comment]
This is due to async.
