### ISSUE TITLE
add md5

### ISSUE THREAD

**Issue by ondraczsk** [DaPigGuy/PiggyAuth#80]
I only want to have md5 hashing for my web auth

**Comment by DaPigGuy** [comment]
Hell no.

**Comment by Thunder33345** [comment]
@ondraczsk even tho it's not recommended, and we wont provide any support for you, if you are determined enough there's a button called "fork" at there you can hack and slash your code however you want
dont ask me how, asking me how just prove you are incapable of doing things right
OR alternatively even better just use the hash algorithm piggy auth uses
