### ISSUE TITLE
error

### ISSUE THREAD

**Issue by daniktheboss** [DaPigGuy/PiggyAuth#82]
error with plugin. test with tesseract

**Comment by daniktheboss** [comment]
12:17:56 [CRITICAL] Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'NameCorrector v1.0.0#build011': Class pocketmine\network\protocol\Info not found on NameCorrector\NameCorrector
12:17:56 [CRITICAL] ClassNotFoundException: "Class pocketmine\network\protocol\Info not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by Thunder33345** [comment]
wrong repo? lol
