### ISSUE TITLE
Feature Request: Unregister from Console

### ISSUE THREAD

**Issue by nasiridrishi** [DaPigGuy/PiggyAuth#83]
Can you add so we can unregister/reset players password from console please!!
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuth
- * [ ] Have a detailed title like "Players are being kicked randomly"
- * [ ] Provide any crash dumps or errors

#### **Data Provider:**

- [ ] MySQL
- [ ] SQLite
- [ ] YAML
- [ ] JSON

#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
Um, resetpassword?...
