### ISSUE TITLE
Bug MySQL Provider

### ISSUE THREAD

**Issue by tosterdev** [DaPigGuy/PiggyAuth#84]
I use the mysql provider often appears bug ErrorException: "mysqli::ping(): MySQL server has gone away" (EXCEPTION) in "/PiggyAuth-master/src/PiggyAuth/Tasks/PingTask" at line 34

# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [x] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [x] Make sure you are on the latest version of PMMP & PiggyAuth
- * [ ] Have a detailed title like "Players are being kicked randomly"
- * [ ] Provide any crash dumps or errors

General

Server Software:

Version of PiggyAuth:

#### **Data Provider:**

- [x] MySQL
- [ ] SQLite
- [ ] YAML
- [ ] JSON

**Comment by DaPigGuy** [comment]
That means that connection to the MySQL db was lost.

**Comment by Aericio** [comment]
are you connecting to your mysql server by localhost or tcp/udp?

**Comment by tosterdev** [comment]
I'm using tcp connection

**Comment by tosterdev** [comment]
localhost also error occurs [12:49:57] [Server thread/CRITICAL]: Could not execute task PiggyAuth\Tasks\PingTask: mysqli::ping(): MySQL server has gone away
[12:49:57] [Server thread/CRITICAL]: ErrorException: "mysqli::ping(): MySQL server has gone away" (EXCEPTION) in "/PiggyAuth-master/src/PiggyAuth/Tasks/PingTask" at line 34
[12:50:12] [Server thread/ERROR]: [PiggyAuth] Connection to MySQL Database lost.
#MySQL login
mysql:
  host: 127.0.0.1
  user: servers
  name: servers
  password: password
  port: 3306
