### ISSUE TITLE
Error: Call to a member function isAuthenticated() on null

### ISSUE THREAD

**Issue by nasiridrishi** [DaPigGuy/PiggyAuth#85]
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuth
- * [ ] Have a detailed title like "Players are being kicked randomly"
- * [ ] Provide any crash dumps or errors

#### **General**
15.06 13:28:15 [Server] Server thread/CRITICAL Error: "Call to a member function isAuthenticated() on null" (EXCEPTION) in "/PiggyAuth.phar/src/PiggyAuth/EventListener" at line 85

#### **Data Provider:**

- [x] MySQL
- [ ] SQLite
- [ ] YAML
- [ ] JSON

#### **Steps to Reproduce the Issue**

1.

**Comment by Aericio** [comment]
What are the steps to reproduce the issue? We have a template for a reason.

**Comment by nasiridrishi** [comment]
This error spams when I reload server and cause server to restart!!!!

**Comment by nasiridrishi** [comment]
I am using mysql
