### ISSUE TITLE
plugin is working awesome but causes problem in restart or reload. it keep crashing with error:-

### ISSUE THREAD

**Issue by nasiridrishi** [DaPigGuy/PiggyAuth#90]
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuth
- * [ ] Have a detailed title like "Players are being kicked randomly"
- * [ ] Provide any crash dumps or errors

#### **Data Provider:**

- [x] MySQL
- [ ] SQLite
- [ ] YAML
- [ ] JSON

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

24.06 16:51:14 [Server] Server thread/CRITICAL Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'PiggyAuth v3.0.0.20': Call to a member function isAuthenticated() on null on PiggyAuth\EventListener
24.06 16:51:14 [Server] Server thread/CRITICAL Error: "Call to a member function isAuthenticated() on null" (EXCEPTION) in "PiggyAuth.phar/src/PiggyAuth/EventListener" at line 374

**Comment by DaPigGuy** [comment]
Are you sure you're using the latest build from Poggit?

**Comment by nasiridrishi** [comment]
Yes

**Comment by Aericio** [comment]
@optimusprime338 please, next time actually fill out information and not just crashdump.

**Comment by nasiridrishi** [comment]
ok thanks
