### ISSUE TITLE
options of email

### ISSUE THREAD

**Issue by nasiridrishi** [DaPigGuy/PiggyAuth#91]
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuth
- * [ ] Have a detailed title like "Players are being kicked randomly"
- * [ ] Provide any crash dumps or errors

#### **Data Provider:**

- [x] MySQL
- [ ] SQLite
- [ ] YAML
- [ ] JSON

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

Email dont work when a player tries to register . I mean to say when they type email it response nothing and most of the player get confused when I see logs. can you add an option so i dont ask for email till this  issue is fixed please.
Thanks

**Comment by Aericio** [comment]
Are you using the latest version of PiggyAuth, and what server software? We ask you to put it there for a reason.

**Comment by nasiridrishi** [comment]
Using latest version..

**Comment by nasiridrishi** [comment]
lots of player just do /register password password coz they are used to and when they do /register passwors password email it just dont work .. I m using it in my main server and cant take it back coz of lots of registrations ,., please disable this email system fr now.

**Comment by nasiridrishi** [comment]
@Aericio  what server softwarer do you use .. you server is awesome.. main point is that it works awesome in ur server. Can I know the soft?

**Comment by nasiridrishi** [comment]
there is problem with mysql its not working properly with mysql with error:-
Server thread/CRITICAL Error: "Call to a member function isAuthenticated() on null" (EXCEPTION) in "/PiggyAuth.phar/src/PiggyAuth/EventListener" at line 328
