### ISSUE TITLE
Register wont work

### ISSUE THREAD

**Issue by FunnyBuddys** [DaPigGuy/PiggyAuth#92]
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [x] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyAuth
- * [x] Have a detailed title like "Players are being kicked randomly"
- * [x] Provide any crash dumps or errors

#### **Server Software:**

PMMP

#### **Version of PiggyAuth:**

3.0.0.20
#### **Data Provider:**

- [x] MySQL
- [ ] SQLite
- [ ] YAML
- [ ] JSON

#### **Steps to Reproduce the Issue**

1. Try to Register

#### **Extra Information**
[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerCommandPreprocessEvent' to 'PiggyAuth v3.0.0.20': Uninitialized string offset: 1 on PiggyAuth\EventListener

[Server thread/CRITICAL]: ErrorException: "Uninitialized string offset: 1" (EXCEPTION) in "plugins/PiggyAuth-master/src/PiggyAuth/EventListener" at line 233 --

**Comment by nasiridrishi** [comment]
do ./register password password none
you can type none in place of email . email dont work .idk why

**Comment by FunnyBuddys** [comment]
Can i disable the Email thing manually?

**Comment by SleepSpace9** [comment]
Because the "else" (https://github.com/DaPigGuy/PiggyAuth/blob/8404e1fda18e1d727de93d4d0cd3e728ee01884a/src/PiggyAuth/Commands/PreregisterCommand.php#L48) is not needed.
If the user enters no email then the argument is automatically set to "none", because of the "else" the rest of the code will not be executed, but should!

**Comment by nasiridrishi** [comment]
Actually I started using it on my main server and having lots of problems!!

**Comment by SalmonDE** [comment]
@SleepSpace9 Could you create a pr for that? Also, is this really why this issue occurs?

**Comment by SleepSpace9** [comment]
@SalmonDE Sorry, I skimmed a bit too quickly through the issue description and only remembered a previously fixed issue on @AppleMinerHD's server when the player enters no value for email address. Sadly I didn't have much time so far to create a PR, I was always in a rush and didn't want to use the web editor. 😉

**Comment by SalmonDE** [comment]
darn, I was planning to fix this. ;(

**Comment by nasiridrishi** [comment]
Email thingy is still not working ..so can you add where players don't have/forced to enter email/"none" coz they are kid's they only know to type /register password password email and it doesn't work .. so they just have you type /register password password ..it would be awesome

**Comment by DaPigGuy** [comment]
We just did that -_-

**Comment by nasiridrishi** [comment]
What I tested with latest version/commit.. I will try again
