### ISSUE TITLE
Lots of CPU uses:

### ISSUE THREAD

**Issue by nasiridrishi** [DaPigGuy/PiggyAuth#94]
[#](url) DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [ y] Be using PMMP
- * [y ] Make sure the issue hasn't already been reported
- * [y ] Make sure you are on the latest version of PMMP & PiggyAuth
- * [y ] Have a detailed title like "Players are being kicked randomly"
- * [ ] Provide any crash dumps or errors

#### **Data Provider:**

- [y ] MySQL
- [ ] SQLite
- [ ] YAML
- [ ] JSON

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

https://timings.pmmp.io/?url=25106810
This plugins eating lots of my CPU uses!!
I will request to remove boss thing ,, it keep spawning wither under spawn. idk how!!

**Comment by Aericio** [comment]
In piggyauth's configuration file, you can disable the boss bar.

**Comment by nasiridrishi** [comment]
Isn't this even related to piggy auth?:-  " 38.50%	  62.24%	1,301.57 s	    31.12 ms	 381	  15,922.5k	    Player Network Receive"

**Comment by Aericio** [comment]
That isn't related to PiggyAuth, I think that is the receive packets from doing things in the server.

**Comment by nasiridrishi** [comment]
one more question, why is email working on spoons like genesis but not in official pmmp latest version?

**Comment by Aericio** [comment]
possibly pmmp breaking changes for that were not fixed yet? idk.

**Comment by Aericio** [comment]
Anyways, this is not PiggyAuth's fault. Closing issue.
