### ISSUE TITLE
Suggestion for the capes

### ISSUE THREAD

**Issue by EpicPinkCreeper** [DaPigGuy/PiggyAuth#97]
Hello! I really like this plugin.  I really like the capes especially since I can not find any other plugins with capes. I was wondering if you could add a command to choose a cape, maybe a setting in the config or even a way to add our own capes.

**Comment by Aericio** [comment]
https://github.com/salmonde/skinchanger
^ /changecape.

Allowing a command to change the cape in an _auth_ plugin is unnecessary.
